// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/getAddressFromPostalCode.ts";
import * as $$$0 from "./loaders/ArCo/getListOfSpecifications.tsx";
import * as $$$1 from "./loaders/storeConfig.ts";

const manifest = {
  "loaders": {
    "deco-components/loaders/ArCo/getListOfSpecifications.tsx": $$$0,
    "deco-components/loaders/storeConfig.ts": $$$1,
  },
  "actions": {
    "deco-components/actions/getAddressFromPostalCode.ts": $$$$$$$$$0,
  },
  "name": "deco-components",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
